### ISSUE TITLE
Dit script is identiek aan dat van Damien

### ISSUE THREAD

**Issue by Theo-denBlanken** [Spyrincho/JavascriptModal#1]
dat is erg onwaarschijnlijk als je onafhankelijk van elkaar 6 namen bedenkt.

**Comment by Spyrincho** [comment]
Ik heb de code speciaal aangepast zodat het er niet meer op lijkt, ook al had ik het orgineel ook zo geschreven. Het zijn simpele namen om mee op te komen. Ik heb ook niks gekopieerd van Damien. Ik heb het van de laatste keer met de formulieren opdracht geleerd dat als ik of iemand anders code kopieerd een slecht cijfer er uit komt. Dit was niet bedoeld. De code staat er nu anders op. Nogmaals, ik heb niks gekopieerd, en het was niet mijn bedoeling om het er op te laten lijken.
